# 不同的环境使用不同的配置
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
# 测试环境：java -jar xxx.jar --spring.profiles.active=test
# 生产环境：java -jar xxx.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  datasource:
    # mysql
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 默认使用Tomcat自带db连接池
    maximum-pool-size: 30
    max-idle: 15
    max-wait: 5000
    min-idle: 10
    initial-size: 15
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml

#下面这一行务必不能少，区分不同配置，而且必须是三个字符"-"
---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/cfdb_2018-01-08?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf8

---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/cfdb_2018-01-08?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf8

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/cfdb_2018-01-08?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf8